// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug 27 01:31:51 2010

#include <wx/wx.h>
#include <wx/image.h>
#include <sys/time.h>
#include "core/core.h"
#include "interface/calc.h"
#include "wxgui.h"
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef WXGUI_LCD_H
#define WXGUI_LCD_H


// begin wxGlade: ::extracode
// end wxGlade

enum {
    wxWabbitemu_Timer = wxID_HIGHEST,
    
}
class wxWabbitemu_LCD: public wxFrame {
public:
    // begin wxGlade: wxWabbitemu_LCD::ids
    // end wxGlade

    wxWabbitemu_LCD(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

protected:
    // begin wxGlade: wxWabbitemu_LCD::attributes
    wxStaticText* label_1;
    wxPanel* panel_1;
    wxTimer* wabbitemu_Timer;
	void OnTimer(wxTimerEvent& event);
    void OnPaint(wxPaintEvent& event);
    // end wxGlade
    
private:
    // begin wxGlade: wxWabbitemu_LCD::methods
    void set_properties();
    void do_layout();
    void PaintLCD(wxFrame *, wxPaintDC);
    // end wxGlade
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class

BEGIN_EVENT_TABLE(wxWabbitemu_LCD, wxFrame)
    EVT_TIMER(wxWabbitemu_Timer, wxWabbitemu_LCD::OnTimer)
    EVT_PAINT(wxWabbitemu_LCD::OnPaint)
END_EVENT_TABLE()

#endif // WXGUI_LCD_H


